# Generated by Django 2.0 on 2018-02-14 21:29

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_wizard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
