# Generated by Django 2.0 on 2018-01-18 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy_wizard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policies',
            name='policy_template_id',
        ),
        migrations.AddField(
            model_name='policies',
            name='related_template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_policies', to='policy_wizard.PolicyTemplates'),
        ),
        migrations.AlterField(
            model_name='policies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='policies',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policies',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='policytemplates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='policytemplates',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
