# Generated by Django 3.1.12 on 2021-06-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_wizard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
