# Generated by Django 2.0 on 2018-03-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_wizard', '0002_auto_20180214_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policies',
            name='context_id',
        ),
    ]
