# Generated by Django 2.0 on 2018-02-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_wizard', '0002_auto_20180118_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies',
            name='context_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
