# Generated by Django 2.0 on 2018-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_wizard', '0002_auto_20180214_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='context_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
