# Generated by Django 2.0 on 2018-03-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_wizard', '0003_remove_policies_context_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies',
            name='context_id',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
